# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_content',
            field=models.CharField(max_length=40),
        ),
    ]
