# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followable',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.ManyToManyField(related_name='followed_by', to='grumblr.Profile'),
        ),
    ]
