# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0005_remove_profile_followable'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followable',
            field=models.IntegerField(default=1),
        ),
    ]
