# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0007_auto_20171007_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followable',
        ),
    ]
