# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0012_auto_20171008_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
